[package]
name = "resast"
version = "0.4.0-beta-2"
authors = ["rfm <r@robertmasen.pizza>"]
edition = "2018"
description = "Rusty-ECMAScript Abstract Syntax Tree"
repository = "https://github.com/FreeMasen/resast"
license = "MIT"
keywords = ["JavaScript", "parsing", "JS", "ES", "ECMA"]
categories = ["parsing", "text-processing", "web-programming"]

[dependencies]
serde = "1"
serde_derive = "1"
unescape = "0.1"

[dev-dependencies]
serde_json = "1"
ressa = { path = "../ressa" }#"0.7.0-beta-1"

[patch.crates-io]
resast = { path = "." }