[package]
name = "derive_as_concrete"
version = "0.1.0"
authors = ["rmasen"]
edition = "2018"


[dependencies]
quote = "0.6"
proc-macro2 = "0.4"
syn = { version = "0.15", features = ["full"] }

[lib]
proc-macro = true